UrlShortener.MVC/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using UrlShortener.MVC.Data.Entities.Identities;

namespace UrlShortener.MVC.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<UrlShortenerUser> _signInManager;
        private readonly UserManager<UrlShortenerUser> _userManager;
        private readonly IUserStore<UrlShortenerUser> _userStore;
        private readonly IUserEmailStore<UrlShortenerUser> _emailStore;
        private readonly IEmailSender _emailSender;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<UrlShortenerUser> signInManager,
            UserManager<UrlShortenerUser> userManager,
            IUserStore<UrlShortenerUser> userStore,
            ILogger<ExternalLoginModel> logger,
            IEmailSender emailSender)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _userStore = userStore;
            _emailStore = GetEmailStore();
            _logger = logger;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ProviderDisplayName { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }
        
        public IActionResult OnGet() => RedirectToPage("./Login");

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                ProviderDisplayName = info.ProviderDisplayName;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
                var user = CreateUser();

                await _userStore.SetUserNameAsync(user, Input.Email, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, Input.Email, CancellationToken.None);

                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);

                        var userId = await _userManager.GetUserIdAsync(user);
                        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                        var callbackUrl = Url.Page(
                            "/Account/ConfirmEmail",
                            pageHandler: null,
                            values: new { area = "Identity", userId = userId, code = code },
                            protocol: Request.Scheme);

                        await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                            $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                        // If account confirmation is required, we need to show the link if we don't have a real email sender
                        if (_userManager.Options.SignIn.RequireConfirmedAccount)
                        {
                            return RedirectToPage("./RegisterConfirmation", new { Email = Input.Email });
                        }

                        await _signInManager.SignInAsync(user, isPersistent: false, info.LoginProvider);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            ProviderDisplayName = info.ProviderDisplayName;
            ReturnUrl = returnUrl;
            return Page();
        }

        private UrlShortenerUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<UrlShortenerUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(UrlShortenerUser)}'. " +
                    $"Ensure that '{nameof(UrlShortenerUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the external login page in /Areas/Identity/Pages/Account/ExternalLogin.cshtml");
            }
        }

        private IUserEmailStore<UrlShortenerUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<UrlShortenerUser>)_userStore;
        }
    }
}

UrlShortener.MVC/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using UrlShortener.MVC.Data.Entities.Identities;

namespace UrlShortener.MVC.Areas.Identity.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<UrlShortenerUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<UrlShortenerUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

UrlShortener.MVC/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UrlShortener.MVC.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

UrlShortener.MVC/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using UrlShortener.MVC.Data.Entities.Identities;

namespace UrlShortener.MVC.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterConfirmationModel : PageModel
    {
        private readonly UserManager<UrlShortenerUser> _userManager;
        private readonly IEmailSender _sender;

        public RegisterConfirmationModel(UserManager<UrlShortenerUser> userManager, IEmailSender sender)
        {
            _userManager = userManager;
            _sender = sender;
        }

        public string Email { get; set; }
        public bool DisplayConfirmAccountLink { get; set; }
        public string EmailConfirmationUrl { get; set; }

        public async Task<IActionResult> OnGetAsync(string email, string returnUrl = null)
        {
            if (email == null)
            {
                return RedirectToPage("/Index");
            }
            returnUrl = returnUrl ?? Url.Content("~/");

            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
                return NotFound($"Unable to load user with email '{email}'.");
            }

            Email = email;
            // Once you add a real email sender, you should remove this code that lets you confirm the account
            DisplayConfirmAccountLink = true;

            if (DisplayConfirmAccountLink)
            {
                var userId = await _userManager.GetUserIdAsync(user);
                var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                EmailConfirmationUrl = Url.Page(
                    "/Account/ConfirmEmail",
                    pageHandler: null,
                    values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
                    protocol: Request.Scheme);
            }

            return Page();
        }
    }
}

UrlShortener.MVC/Views/Authentication/ExternalLogin.cshtml
@model UrlShortener.MVC.Models.Identities.ExternalLoginVM

@{
    ViewData["Title"] = "Register";
}

<h1>@ViewData["Title"]</h1>
<h2 id="external-login-title">Associate your @Model.ProviderDisplayName account.</h2>
<hr />

<p id="external-login-description" class="text-info">
    You've successfully authenticated with <strong>@Model.ProviderDisplayName</strong>.
    Please enter an email address for this site below and click the Register button to finish
    logging in.
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <div class="form-floating mb-3">
                <input asp-for="Email" class="form-control" autocomplete="email" placeholder="Please enter your email." />
                <label asp-for="Email" class="form-label"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="w-100 btn btn-lg btn-primary">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

UrlShortener.MVC/Views/Authentication/ForgotPassword.cshtml
@model UrlShortener.MVC.Models.Identities.VerifyOtpVM

@{
    ViewData["Title"] = "Forgot your password?";
}

<h1>@ViewData["Title"]</h1>
<h2>Enter your email to receive a reset code.</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ForgotPassword" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <div class="form-floating mb-3">
                <input asp-for="Email" class="form-control" autocomplete="username" aria-required="true" placeholder="name@example.com" />
                <label asp-for="Email">Email</label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="w-100 btn btn-lg btn-primary">Send Reset Code</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

UrlShortener.MVC/Views/Authentication/ForgotPasswordConfirmation.cshtml
@model UrlShortener.MVC.Models.Identities.VerifyOtpVM
@{
    ViewData["Title"] = "Reset password confirmation";
}

<h1>@ViewData["Title"]</h1>
<p>
    Your password has been reset. Please <a asp-page="./Login">click here to log in</a>.
</p>

UrlShortener.MVC/Views/Authentication/RegisterConfirmation.cshtml
@model UrlShortener.MVC.Models.Identities.RegisterConfirmationVM
@{
    ViewData["Title"] = "Verify Email";
}

<h1>Confirm your account.</h1>

@if (Model != null)
{
    <div class="container py-4">
        <p class="text-muted">We have sent a confirmation email to <strong>@Model.Email</strong>.</p>
        <div class="alert alert-info">
            Please check your inbox and click the link to activate your account.
            <br />
            Tip: If you don't see it in your Inbox, please also check the <b>Spam/Junk</b> folder.
        </div>
        <form asp-action="RegisterConfirmation" method="post">
            @Html.AntiForgeryToken()
            <input asp-for="ReturnUrl" type="hidden" />
            <input asp-for="Email" type="hidden" />
            <input asp-for="UserId" type="hidden" />
            <input asp-for="Code" type="hidden" />
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>


        <div>Or Click Confirm to confirm your account</div>
        <button type="submit" class=" btn btn-primary">Confirm</button>
        </form>
        <br />
        <a class="btn btn-primary" asp-page="/Account/Login">Back to Login</a>
        @* (Tuỳ chọn) Hiện thêm link gửi lại *@
        @* <div class="mt-3">
       Bạn chưa nhận được email?
        <a asp-controller="Authentication" asp-action="ResendConfirmation" asp-route-email="@Model.Email">Gửi lại</a>
    </div> *@
    </div>

}

UrlShortener.MVC/Views/Authentication/VerifyOtp.cshtml
@model UrlShortener.MVC.Models.Identities.VerifyOtpVM
@{
    ViewData["Title"] = "Verify Email";
}

<div class="container py-5" style="max-width:480px; text-align:center;">
    <a href="/Authentication/Register" class="text-muted mb-3 d-block">← Back to Sign Up</a>
    <div class="mb-4">
        <img src="/images/verify-icon.svg" alt="Verify Icon" style="width:64px; height:64px;" />
    </div>
    <h3 class="mb-3" style="color:#6c63ff;">Verify Your Email</h3>
    <p class="text-muted">We've sent a 6-digit code to <b>@Model.Email</b>. It expires in 10 minutes.</p>

    <!-- Display global errors -->
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <div>@error.ErrorMessage</div>
            }
        </div>
    }

    <form asp-action="VerifyOtp" method="post" class="mt-3" onsubmit="combineOtpInputs()">
        <input type="hidden" asp-for="Email" />
        <input type="hidden" asp-for="Purpose" />
        <input type="hidden" asp-for="ReturnUrl" />
        <input type="hidden" id="Otp" name="Otp" />

        <div class="mb-3 d-flex justify-content-center gap-2">
            @for (int i = 0; i < 6; i++)
            {
                <input type="text" maxlength="1" class="form-control text-center otp-input"
                       style="width:50px; height:50px; font-size:24px;"
                       oninput="moveToNext(this, @i)" />
            }
        </div>
        <span asp-validation-for="Otp" class="text-danger"></span>

        <button type="submit" class="btn btn-primary w-100 mt-3" style="background-color:#6c63ff; border:none;">Verify Email</button>
    </form>

    <form asp-action="ResendOtp" method="post" class="mt-3">
        <input type="hidden" name="email" value="@Model.Email" />
        <input type="hidden" name="purpose" value="@Model.Purpose" />
        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
        <button class="btn btn-link p-0 text-muted">Resend code in <span id="resend-timer">60s</span></button>
    </form>

    <p class="text-muted mt-3">Didn't receive the email? Check your spam folder or try resending.</p>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        let timer = 60;
        const timerElement = document.getElementById('resend-timer');
        const interval = setInterval(() => {
            timer--;
            timerElement.textContent = `${timer}s`;
            if (timer <= 0) {
                clearInterval(interval);
                timerElement.textContent = 'now';
            }
        }, 1000);

        function moveToNext(currentInput, index) {
            const inputs = document.querySelectorAll('.otp-input');
            if (currentInput.value.length === 1 && index < inputs.length - 1) {
                inputs[index + 1].focus();
            } else if (currentInput.value.length === 0 && index > 0) {
                inputs[index - 1].focus();
            }
        }

        document.querySelectorAll('.otp-input').forEach(input => {
            input.addEventListener('keydown', (e) => {
                if (!/^\d$/.test(e.key) && e.key !== 'Backspace' && e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') {
                    e.preventDefault();
                }
                if (e.key === 'Enter') {
                    const otpInputs = document.querySelectorAll('.otp-input');
                    const allFilled = Array.from(otpInputs).every(input => input.value.length === 1);
                    if (allFilled) {
                        combineOtpInputs();
                        document.querySelector('form[asp-action="VerifyOtp"]').submit();
                    }
                }
            });
        });

        function combineOtpInputs() {
            const inputs = document.querySelectorAll('.otp-input');
            const otpValue = Array.from(inputs).map(input => input.value).join('');
            document.getElementById('Otp').value = otpValue;
        }
    </script>
}

@* @model UrlShortener.MVC.Models.Identities.VerifyOtpVM
@{
    ViewData["Title"] = "Verify Email";
}

<div class="container py-5" style="max-width:480px">
    <h3 class="mb-3">Enter verification code</h3>
    <p class="text-muted">We sent a 6-digit code to <b>@Model.Email</b>. It expires in 10 minutes.</p>

    <!-- ✅ HIỂN THỊ LỖI TOÀN CỤC -->
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <div>@error.ErrorMessage</div>
            }
        </div>
    }

    <form asp-action="VerifyOtp" method="post" class="mt-3">
        <input type="hidden" asp-for="Email" />
        <input type="hidden" asp-for="Purpose" />
        <input type="hidden" asp-for="ReturnUrl" />

        <div class="mb-3">
            <label asp-for="Otp" class="form-label">OTP</label>
            <input asp-for="Otp" class="form-control" placeholder="123456" autocomplete="one-time-code" />
            <span asp-validation-for="Otp" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary w-100">Verify</button>
    </form>

    <form asp-action="ResendOtp" method="post" class="mt-3">
        <input type="hidden" name="email" value="@Model.Email" />
        <input type="hidden" name="purpose" value="@Model.Purpose" />
        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
        <button class="btn btn-link p-0">Resend code</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
} *@